image: library/golang:1.22
pipelines:
  default:
    - step:
        runs-on:
          - self.hosted
          - linux
        name: go-build
        script:
          - git submodule sync
          - git submodule update --init --recursive
          - go env -w GOFLAGS="-buildvcs=false"
          - cd baserepo
          - go build
