version: 2.1
orbs: 
  go: circleci/go@1.11.0
jobs:
  go-build:
    executor: 
      name: go/default
      tag: 1.22.5
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: "go install"
          command: |
            cd baserepo
            go build

workflows:
  go-build-workflow:
    jobs:
     - go-build
